Allow for properties with missing or empty values.
prowave/chargify-webhook-java pull request #3
Opened 2016-11-11 07:19 UTC by aontas

Sometimes there are properties that have empty values. This is more likely to happen when receiving a subscription based payload, as they have properties that are not required.

As "trailing empty strings are not included in the array" (from java docs: http://docs.oracle.com/javase/7/docs/api/java/lang/String.html), manually setting the empty string is an appropriate alternative to an index out of bounds exception.

2016-11-14 15:15 UTC, prowave requested changes
Please create a unit test for your change.

My main concern is what the String "pair" looks like when the value is empty.

Is it "key" or "key=" ?  

Thanks for the PR.

2016-11-15 00:12 UTC, aontas commented
Given your current code, it wouldn't really make a difference (as the split would still return the first part sans the equals).

None the less, it is off the form "key=".

Where/how would you like the unit test? It may just be me, but I cannot seem to see any existing tests for me to add it to.

2016-12-06 15:30 UTC, merged

2016-12-06 15:31 UTC, prowave commented
Merged.

2016-12-21 14:29 UTC, prowave commented
Change applied to 1.0.5, merged into master and deployed to central maven repo.  Thanks @aontas